version: "3.6"

services:
  back:
    build:
      context: back
      dockerfile: Dockerfile
      target: production
    command: gunicorn my2a.wsgi:application --bind 0.0.0.0:8000
    env_file: .env
    restart: always
    volumes:
      - ./back:/src
      - ./backups:/backups
      - backdata:/src/static
    networks:
      - nginx_link
  redis:
    image: redis:7.2.2-bookworm
    command: redis-server --save 60 1 --loglevel notice --requirepass ${REDIS_PASSWORD}
    restart: always
    volumes:
      - cache:/data
    networks:
      - cache_link
    healthcheck:
        test: echo 'auth ${REDIS_PASSWORD}\nping' | redis-cli | grep PONG
        interval: 5s
        timeout: 3s
        retries: 5
  front:
    build:
      context: front
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./front:/app
      - webdata:/output
    networks:
      - nginx_link
  nginx:
    build: 
      context: nginx
      dockerfile: Dockerfile
      target: production
    ports:
      - "3154:80"
    restart: always
    networks:
      - nginx_link
    depends_on:
      - back
      - front
    volumes:
      - webdata:/webdata
      - backdata:/backdata/static
networks:
  nginx_link:
    driver: bridge
  cache_link:

volumes:
  webdata:
  backdata:
  cache:

