version: "3.6"

services:
  back:
    build:
      context: back
      dockerfile: Dockerfile
      target: production
    command: gunicorn my2a.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - path: ./.env-example
        required: true 
      - path: ./.env
        required: false
    restart: always
    volumes:
      - ./back:/src
      - ./backups:/backups
      - backdata:/src/static
    networks:
      - nginx_link
  front:
    build:
      context: front
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./front:/app
      - webdata:/output
    networks:
      - nginx_link
  nginx:
    build: 
      context: nginx
      dockerfile: Dockerfile
      target: production
    ports:
      - "3154:80"
    restart: always
    networks:
      - nginx_link
    depends_on:
      - back
      - front
    volumes:
      - webdata:/webdata
      - backdata:/backdata/static
networks:
  nginx_link:
    driver: bridge

volumes:
  webdata:
  backdata:
