# Generated by Django 4.2.6 on 2025-01-20 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0020_department_end_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_of_the_school_year', models.DateField()),
                ('start_of_S3B', models.DateField()),
                ('start_of_S4A', models.DateField()),
                ('start_of_S4B', models.DateField()),
                ('end_of_school_year', models.DateField()),
                ('monday_of_autumn_holiday', models.DateField()),
                ('moday_of_xmas_holiday', models.DateField()),
                ('monday_of_winter_holiday', models.DateField()),
                ('monday_of_spring_holiday', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('is_public_holiday', models.BooleanField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.department')),
            ],
        ),
    ]
