# Generated by Django 4.2.6 on 2024-11-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0020_department_end_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('S3', 'S3'), ('S4', 'S4'), ('S3A', 'S3A'), ('S3B', 'S3B'), ('S4A', 'S4A'), ('S4B', 'S4B')], max_length=10),
        ),
    ]
