# Generated by Django 4.2.6 on 2025-01-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0021_alter_course_semester'),
        ('education', '0021_yearinformation_specialday'),
    ]

    operations = [
    ]
