# Generated by Django 4.2.6 on 2025-01-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0021_alter_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.CharField(max_length=10),
        ),
    ]
