# Generated by Django 4.2.6 on 2025-01-21 23:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0022_merge_20250120_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialday',
            name='department',
        ),
        migrations.RemoveField(
            model_name='specialday',
            name='is_public_holiday',
        ),
        migrations.RemoveField(
            model_name='yearinformation',
            name='moday_of_xmas_holiday',
        ),
        migrations.AddField(
            model_name='yearinformation',
            name='ascension_day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='yearinformation',
            name='easter_monday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='yearinformation',
            name='monday_of_xmas_holiday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='yearinformation',
            name='whit_monday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='yearinformation',
            name='end_of_school_year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='yearinformation',
            name='monday_of_autumn_holiday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='yearinformation',
            name='monday_of_spring_holiday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='yearinformation',
            name='monday_of_winter_holiday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='yearinformation',
            name='start_of_S3B',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='yearinformation',
            name='start_of_S4A',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='yearinformation',
            name='start_of_S4B',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='yearinformation',
            name='start_of_the_school_year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
