# Generated by Django 4.2.6 on 2025-01-25 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0022_alter_course_day'),
        ('education', '0023_remove_specialday_department_and_more'),
    ]

    operations = [
    ]
