# Generated by Django 4.2.6 on 2025-02-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0022_merge_20250124_1801'),
        ('education', '0024_merge_20250125_2023'),
    ]

    operations = [
    ]
