# Generated by Django 4.2.6 on 2025-05-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0025_merge_20250208_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('2A', 'A2'), ('3A', 'A3')], default='2A', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6'), ('S3A', 'S3A'), ('S3B', 'S3B'), ('S4A', 'S4A'), ('S4B', 'S4B'), ('S5A', 'S5A'), ('S5B', 'S5B'), ('S6A', 'S6A'), ('S6B', 'S6B')], max_length=10),
        ),
    ]
