name: CI
on:
  pull_request:
  push:
    branches:
      - login
jobs:
  test-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build containers
        run: docker compose build
      - name: Start containers
        run: docker compose up -d

  test-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build containers
        run: docker compose -f docker-compose-prod.yml build
      - name: Start containers
        run: docker compose up -f docker-compose-prod.yml -d

  test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install linter
        run: pip install black flake8 isort
      - name: Lint
        run: black . --check && isort . --profile black && flake8 . --config .github/linters/.flake8
